services:
  - type: web
    name: gestor-finanzas-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 8080
      - key: BOT_TOKEN
        sync: false
      - key: ALLOWED_USER_ID
        sync: false
      - key: TURSO_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false